### ISSUE TITLE
Taglib2 tests build failure with commit #785

### ISSUE THREAD

**Issue by FestusHagen** [taglib/taglib#786]
```[ 75%] Building CXX object tests/CMakeFiles/test_runner.dir/test_mpeg.cpp.obj
\taglib\taglib\tests\test_mpeg.cpp: In member function 'void TestMPEG::testAudioPropertiesXingHeaderCBR()':
\taglib\taglib\tests\test_mpeg.cpp:73:50: error: no matching function for call to 'TagLib::MPEG::File::File(const char*)'
     MPEG::File f(TEST_FILE_PATH_C("lame_cbr.mp3"));```

Lots of them ...

Windows, MinGW4.9.1

-Enjoy
fh : )_~

**Comment by TsudaKageyu** [comment]
Oops, I missed out on it!

In Win32, the constructors of `File` classes depend on implicit conversion from `const char *` or `const wchar_t *` to `FileName`. So we have to remove `explicit` from `FileName` constructors.

**Comment by TsudaKageyu** [comment]
I have done it. Thanks!

**Comment by FestusHagen** [comment]
Thank you
