### ISSUE TITLE
undefined reference to symbol 'inflateEnd' 

### ISSUE THREAD

**Issue by madamdata** [taglib/taglib#1167]
I'm trying to compile on Ubuntu 22.04 - followed the instructions on the readme and I got this error when I try to run make: 

make  all-recursive
make[1]: Entering directory '/home/ada/Downloads/castget'
Making all in tests
make[2]: Entering directory '/home/ada/Downloads/castget/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ada/Downloads/castget/tests'
Making all in src
make[2]: Entering directory '/home/ada/Downloads/castget/src'
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o castget castget.o channel.o configuration.o date_parsing.o filenames.o htmlent.o libxmlutil.o patterns.o progress.o rss.o urlget.o utils.o -lcurl -lglib-2.0 -lxml2 -L/usr/local/lib -ltag_c -ltag 
libtool: link: gcc -g -O2 -o castget castget.o channel.o configuration.o date_parsing.o filenames.o htmlent.o libxmlutil.o patterns.o progress.o rss.o urlget.o utils.o  -lcurl -lglib-2.0 -lxml2 -L/usr/local/lib -ltag_c -ltag
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libcurl.so: undefined reference to symbol 'inflateEnd'
/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:448: castget] Error 1
make[2]: Leaving directory '/home/ada/Downloads/castget/src'
make[1]: *** [Makefile:556: all-recursive] Error 1
make[1]: Leaving directory '/home/ada/Downloads/castget'
make: *** [Makefile:402: all] Error 2
